site_name: The AI Safety Atlas
site_url: https://ai-safety-atlas.com/textbook/
copyright: MIT; 2023 - 2024 Centre pour la Sécurité de l'IA (CeSIA)

theme:
  name: material
  font:
    text: Benne
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.indexes
    # - navigation.instant  # Consider removing this line
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - toc.integrate
    - toc.follow
  icon:
    logo: material/book-open-page-variant
  palette:
    primary: custom
    accent: custom

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - docs

extra_css:
  - overrides/css/base.css
  - overrides/css/typography.css
  - overrides/css/admonitions.css
  - overrides/css/navigation.css
  - overrides/css/components.css
  - overrides/css/feedback.css
  - overrides/css/tables.css
  - overrides/css/buttons.css
  - https://fonts.googleapis.com/css2?family=Benne&display=swap

extra_javascript:
  - overrides/js/extra.js
  - overrides/js/feedback.js
  - overrides/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - awesome-pages:
      filename: .pages.yml
      collapse_single_pages: false
      strict: false
      order: asc
      sort_type: natural
