# File: textbook/mkdocs.yml
site_name: The AI Safety Atlas
site_url: https://ai-safety-atlas.com

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    #- navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.tacking
    - navigation.path
    - navigation.prune  # render only visible items, improve performance
    #- navigation.expand # auto expands toc
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - toc.follow
    #- toc.integrate


plugins:
  - search
  - awesome-pages:
      filename: .pages.yml
      collapse_single_pages: false
      strict: false
      order: asc
      sort_type: natural
  - glightbox: # https://github.com/blueswen/mkdocs-glightbox
       touchNavigation: true
       loop: false
       effect: zoom
       slide_effect: slide
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes:
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
       background: white
       shadow: true
       manual: false
  - minify: # optimize the site's performance by minifying
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
  - meta-descriptions: # better SEO
      export_csv: false
      quiet: false

use_directory_urls: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
watch:
  - docs

extra_css:
  - overrides/css/base.css
  - overrides/css/buttons.css
  - overrides/css/tippy.css
  - overrides/css/tabs.css
  - overrides/css/typography.css
  - overrides/css/admonitions.css
  - overrides/css/navigation.css
  - overrides/css/metadata.css
  - overrides/css/figures.css
  - overrides/css/footer.css
  - overrides/css/section-end.css
  - overrides/css/scroll-buttons.css
  - https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css


extra_javascript:
  - overrides/js/mathjax.js
  - overrides/js/tippy.js
  - overrides/js/navigation.js
  - overrides/js/scroll-buttons.js
  - https://unpkg.com/@popperjs/core@2
  - https://unpkg.com/tippy.js@6
  - https://unpkg.com/tippy.js@6/dist/animations/perspective-extreme.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  #alternate:
    #- name: English
      #link: /en/ 
      #lang: en
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CentreSecuriteIA/textbook
      name: AI Safety Atlas on GitHub
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/YtatCZ3SQ8
      name: Join our Discord community
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@securite-ia
      name: Subsribe to the youtube channel
  copyright: Copyright &copy; 2024 French Center for AI Safety (CeSIA)
