# File: textbook/mkdocs.yml
site_name: The AI Safety Atlas
site_url: https://ai-safety-atlas.com

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - navigation.sections
    - navigation.tacking
    - navigation.path
    - navigation.prune  # render only visible items, improve performance
    #- navigation.expand # auto expands toc
    - content.tooltips
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - toc.integrate
    - toc.follow

plugins:
  - search
  - awesome-pages:
      filename: .pages.yml
      collapse_single_pages: false
      strict: false
      order: asc
      sort_type: natural

use_directory_urls: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - docs/includes/abbreviations.md
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
watch:
  - docs

extra_css:
  - overrides/css/base.css
  - overrides/css/components.css
  #- overrides/css/404.css
  #- overrides/css/glossary.css
  #- overrides/css/header_footer.css
  #- overrides/css/titles.css
  #- overrides/css/typography.css
  - https://fonts.googleapis.com/css2?family=Benne&display=swap

extra_javascript:
  - overrides/js/mathjax.js
  - overrides/js/glossary.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
