chapter_number: 2
chapter_title: Risks
authors:
- Markov Grey
- Charbel-Raphael Segerie
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- Jeanne Salle
- Charles Martinet
- Vincent Corruble
- Sebastian Gil
- Alejandro Acelas
- Evander Hammer
- Mo Munem
- Mateo Rendon
- Kieron Kretschmar
- Camille Berger
date: '2024-11-20'
links:
- name: Google Docs
  url: https://docs.google.com/document/d/1ifYc49Wq-9HuqCXCa8jIr5n6ZOYjZ3FvxE9vHPMcu58/edit?usp=sharing
  type: google_docs
- name: Feedback
  url: https://forms.gle/ZsA4hEWUx1ZrtQLL9
  type: feedback
- name: Watch
  url: https://www.youtube.com/watch?v=dhr4u-w75aQ
  type: watch
- name: Facilitate
  url: https://docs.google.com/document/d/1evE1rG91DKBuKlWnqPw45QtPxKBz0GlD_ZYrurNdvN4/edit?usp=sharing
  type: facilitate
