authors:
- Charles Martinet
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- Markov Grey
- Charbel-Raphael Segerie
date: '2024-12-10'
links:
- name: AI Safety Atlas
  url: https://ai-safety-atlas.com/chapters/04/
  type: ai_safety_atlas
- name: Google Docs
  url: https://docs.google.com/document/d/1fFVYWes5JQgSc2l9cAMQKprCevw2qW0-4MKMQPnpbxw/edit?usp=sharing
  type: google_docs
