nav:
- Chapter 04: README.md
- 4.1 - Governance Foundations: 01.md
- 4.2 - Governance Targets: 02.md
- 4.3 - Key issues: 03.md
- 4.4 - Corporate Governance: 04.md
- 4.5 - National Governance: 05.md
- 4.6 - International Governance: 06.md
title: 04 - Governance
