title: ''
chapter_number: '1'
authors:
- Markov Grey
- Charbel-Raphael Segerie
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- Jeanne Salle
- Charles Martinet
- Vincent Corruble
date: '2024-11-20'
links:
- name: AI Safety Atlas
  url: https://ai-safety-atlas.com/chapters/01/
  type: ai_safety_atlas
- name: Alignment Forum
  url: https://www.alignmentforum.org/posts/MkfaQyxB9PN4h8Bs9/
  type: alignment_forum
- name: Google Docs
  url: https://docs.google.com/document/d/1HKo0Kest9Xppjn7m2ODpfMUlEu93SzLsfxXBH48Xaus/edit?usp=sharing
  type: google_docs
- name: Feedback
  url: https://forms.gle/ZsA4hEWUx1ZrtQLL9
  type: feedback
- name: Watch
  url: https://www.youtube.com/watch?v=J_iMeH1hb9M
  type: watch
- name: Facilitate
  url: https://docs.google.com/document/d/1L32xCVUCWEsm-x8UZ3GSTgKnmBcC7rJQLLIh9wGLj40/edit?usp=sharing
  type: facilitate
