nav:
- Chapter 01: README.md
- 1.1 - State-of-the-Art AI: 01.md
- 1.2 - Foundation Models: 02.md
- 1.3 - Intelligence: 03.md
- 1.4 - Scaling: 04.md
- 1.5 - Forecasting: 05.md
- 1.6 - Takeoff: 06.md
- Appendix:
  - 1.A1 - Expert Opinions: A1.md
  - 1.A2 - Discussion on LLMs: A2.md
  - 1.A3 - Forecasting - Trends: A3.md
  - 1.A4 - Forecasting - Bio Anchors: A4.md
title: 01 - Capabilities
