nav:
- 1.1 State-of-the-Art AI: 01.md
- 1.2 Foundation Models: 02.md
- 1.3 Terminology: 03.md
- 1.4 Leveraging Computation: 04.md
- 1.5 Forecasting: 05.md
- '1.6 Appendix 1: Expert Opinions': 06.md
- '1.7 Appendix 2: Discussions on LLMs': 07.md
- '1.8 Appendix 3: Trends & Bottlenecks': 08.md
- Overview: README.md
title: 01 - Capabilities
