nav:
- Introduction: README.md
- 1.1 State-of-the-Art AI: 01.md
- 1.2 Foundation Models: 02.md
- 1.3 Intelligence: 03.md
- 1.4 Scaling: 04.md
- 1.5 Forecasting: 05.md
- 1.6 Takeoff: 06.md
- '1.7 Appendix: Expert Opinions': 07.md
- '1.8 Appendix: Discussion on LLMs': 08.md
- '1.9 Appendix: Forecasting - Trends': 09.md
- '1.10 Appendix: Forecasting - Bio Anchors': 10.md
title: 01 - Capabilities
