chapter_number: 7
chapter_title: Generalization
authors:
- Markov Grey
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- RA Writer
- Charbel-Raphael Segerie
- Jeanne Salle
- Oscar Heitmann
- Camille Berger
- Josh Thorsteinson
- Nicolas Guillard
date: '2023-12-13'
links:
- name: Google Docs
  url: https://docs.google.com/document/d/10aqDKJgqonHNc9IMMogtda64u8V_JsPlbuzruBMUmAU/edit?usp=sharing
  type: google_docs
- name: Feedback
  url: https://forms.gle/ZsA4hEWUx1ZrtQLL9
  type: feedback
- name: Facilitate
  url: https://docs.google.com/document/d/1uQooTncb7Hw2NhITtr3S5iGHqT6cvj74c0SZ4Unad_M/edit?usp=sharing
  type: facilitate
