authors:
- Jeanne Salle
- Charbel-Raphael Segerie
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- Markov Grey
date: '2024-11-01'
links:
- name: Google Docs
  url: https://docs.google.com/document/d/1mdYnniBG5vg4HjMMqqojEs8siFXoRnxi0RfxursBw7A/edit?usp=sharing
  type: google_docs
