chapter_number: 8
chapter_title: Scalable Oversight
authors:
- Markov Grey
- Charbel-Raphael Segerie
affiliations:
- French Center for AI Safety (CeSIA)
acknowledgements:
- Jeanne Salle
- Chris Gerrby
- Sebastian Gil
- Josh Thorsteinson
- Nicolas Guillard
- Mateusz Bagiński
- Yoann Poupart
- Clément Dumas
- Amaury Lorin
- Mateo Rendon
- Lucas Eichorn
- Bogdan Ionut Cirstea
- Gurvan R.
date: '2024-07-01'
links:
- name: Google Docs
  url: https://docs.google.com/document/d/1k6rlyBCZJw8xbUx0dzd-4sOhlzj-xzsmwi_OIZY1-3M/edit?usp=sharing
  type: google_docs
- name: Feedback
  url: https://forms.gle/ZsA4hEWUx1ZrtQLL9
  type: feedback
- name: Facilitate
  url: https://docs.google.com/document/d/1DaygDSW0L5dWuJnpSjYPF2XUbW51UoBJsT1cjLYKc2w/edit?usp=sharing
  type: facilitate
