nav:
- 8.1 Introduction: 01.md
- 8.2 Task Decomposition: 02.md
- 8.3 Process Oversight: 03.md
- 8.4 Iterated Amplification (IA): 04.md
- 8.5 Debate: 05.md
- 8.6 Weak-to-Strong (W2S): 06.md
- Overview: README.md
title: 08 - Scalable Oversight
